- id: lys_bad_av
  alias: Belysning bad av
  trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    to: 'off'
    for:
      minutes: 30
  action:
  - service: light.turn_off
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level
  - service: light.turn_off
    entity_id: light.sb_speillys
  - service: switch.turn_off
    entity_id: switch.sb_handkletorker

- id: lys_bad_dim
  alias: Belysning bad dim
  trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    to: 'off'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.sb_speillys
  - condition: state
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level
    state: 'on'
  - service: light.turn_on
    data:
      entity_id: light.qubino_zmnhdd1_flush_dimmer_level
      brightness: 40
  - condition: numeric_state
    entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
    above: 100
  - service: light.turn_off
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level

- id: lys_bad_bevegelse
  alias: Belysning bad på (beveglse)
  trigger:
  - platform: state
    entity_id: binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: group.personer
    state: home
  action:
  - service: switch.turn_on
    entity_id: switch.sb_handkletorker
  - condition: numeric_state
    entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
    below: 300
  - service: light.turn_on
    data:
      entity_id: light.qubino_zmnhdd1_flush_dimmer_level
      brightness: 120
  - service: light.turn_on
    entity_id: light.sb_speillys

- id: lys_av_solopp
  alias: Belysning av (soloppgang)
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: group.all_lights

- id: lys_av_borte
  alias: Innelys av (tomt hus / 3:00)
  trigger:
  - platform: state
    entity_id: group.personer
    to: not_home
    for: 0:30:00
  - platform: time
    at: 03:00:00
  - platform: state
    entity_id: cover.qubino_zmnhod1_flush_shutter_dc_level
    to: closed
    for: 0:30:00
  action:
  - service: light.turn_off
    entity_id: light.innelys

- id: lys_paa_hjem
  alias: Belysning på (hjemkomst)
  trigger:
  - platform: state
    entity_id: group.personer
    to: home
  condition:
  - condition: sun
    after: sunset
  - condition: time
    after: '15:00:00'
    before: 01:00:00
  action:
  - service: scene.turn_on
    entity_id: scene.belysning_dempet

- id: lys_paa_solned
  alias: Belysning på (solnedgang)
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: light.turn_on
    entity_id: light.utelys
  - service: light.turn_on
    entity_id: light.stemningslys
  - condition: state
    entity_id: group.personer
    state: home
  - service: scene.turn_on
    entity_id: scene.belysning_dempet

- id: lys_av_stemning
  alias: Stemningslys av (24:00)
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: light.turn_off
    entity_id: light.stemningslys
  - service: light.turn_off
    entity_id: light.mh_hyllelys

- id: borte_15min
  alias: Støvsug og rullgardiner opp (15 min)
  trigger:
  - platform: state
    entity_id: group.personer
    to: not_home
    for:
      minutes: 15
  action:
  - service: cover.open_cover
    entity_id: cover.qubino_zmnhod1_flush_shutter_dc_level
  - service: vacuum.xiaomi_clean_zone
    data_template:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      repeats: 1
      zone: [[16824,18519,26424,25969]]

- id: vk_nattsenk
  alias: Varmekabler nattsenking
  trigger:
  - platform: time
    at: '16:00:00'
  - platform: time
    at: '23:00:00'
  condition:
  - condition: template
    value_template: '{{states.climate.thermofloor_as_heatit_thermostat_tf_021_heating.attributes.temperature
      > 15}}'
  action:
  - data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_021_heating
      temperature: 20
    service: climate.set_temperature
  - data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_021_heating_2
      temperature: 18
    service: climate.set_temperature

- id: vk_nattsenk_off
  alias: Varmekabler nattsenking av
  trigger:
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '10:30:00'
  condition:
  - condition: template
    value_template: '{{states.climate.thermofloor_as_heatit_thermostat_tf_021_heating.attributes.temperature
      > 15}}'
  action:
  - data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_021_heating
      temperature: 24
    service: climate.set_temperature
  - data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_021_heating_2
      temperature: 22
    service: climate.set_temperature

- id: stromspar_vvb
  alias: Varmtvannsbereder strømsparing
  trigger:
  - platform: time
    at: 05:00:00
  - platform: time
    at: '14:00:00'
  condition:
  - condition: template
    value_template: '{{states.climate.thermofloor_as_heatit_thermostat_tf_021_heating.attributes.temperature
      > 15}}'
  action:
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
  - delay: 00:05:00
  - service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch

- id: stromspar_vvb_off
  alias: Varmtvannsbereder strømsparing av
  trigger:
  - platform: time
    at: '20:00:00'
  - platform: time
    at: '12:00:00'
  condition:
  - condition: template
    value_template: '{{ states.climate.thermofloor_as_heatit_thermostat_tf_021_heating.attributes.temperature
      > 15 }}'
  action:
  - service: switch.turn_on
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
  - delay: 00:05:00
  - service: switch.turn_on
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch

- id: oppdatering
  alias: Home Assistant oppdatering
  trigger:
  - platform: state
    entity_id: sensor.home_assistant_versjon
  action:
  - service: notify.notify
    data_template:
      title: Home Assistant
      message: Versjon {{states.sensor.home_assistant_versjon.state}} er tilgjengelig
      target: Galaxy S9
      data:
        url: https://www.home-assistant.io/latest-release-notes/
        tag: ha-update

- id: rpi_temp_h
  alias: Systemtemperatur høy
  trigger:
  - platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 60
  - platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 65
  - platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 70
  action:
  - service: notify.notify
    data_template:
      title: Home Assistant
      message: 'Alarm: System temperatur er {{states.sensor.cpu_temperatur.state}}°C'
      data:
        tag: pitemp

- id: ask_daglig
  alias: Aksjesparekonto daglig
  trigger:
  - entity_id: sensor.dnb_teknologi_r_1_dag
    platform: state
  condition:
  - after: '10:00:00'
    before: '14:00:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - delay: 00:05
  - data_template:
      data:
        tag: ask-update
        url: http://www.morningstar.no/no/portfoliomanager/portfolio.aspx
      message: 'Beholdning: {{states.sensor.dnb_ask_beholding.state}} kr,

        DNB Health Care R, 1 dag: {{states.sensor.dnb_health_care_r_1_dag.state}}%,

        DNB Teknologi R, 1 dag: {{states.sensor.dnb_teknologi_r_1_dag.state}}%,

        '
      title: Aksjesparekonto
    service: notify.html5_galaxy_s9

- id: openuv
  alias: Oppdater OpenUV data
  trigger:
  - platform: time_pattern
    minutes: /90
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: openuv.update_data
