- id: lys_bad_av
  alias: 'Belysning bad av'
  trigger:
    platform: state
    entity_id: sensor.fibaro_fgms001zw5_burglar
    to: '0'
    for:
      minutes: 20
  action:
    - service: light.turn_off
      entity_id: light.qubino_zmnhdd1_level
    - service: light.turn_off
      entity_id: light.sonoff_basic_3
    - service: switch.turn_off
      entity_id: switch.sonoff_basic_4

- id: lys_bad_dim
  alias: 'Belysning bad dim'
  trigger:
    platform: state
    entity_id: sensor.fibaro_fgms001zw5_burglar
    to: '0'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: light.qubino_zmnhdd1_level
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.qubino_zmnhdd1_level
        brightness: 40
    - service: light.turn_off
      entity_id: light.sonoff_basic_3

- id: lys_bad_paa
  alias: 'Belysning bad på v/beveglse'
  trigger:
    - platform: state
      entity_id: sensor.fibaro_fgms001zw5_burglar
      to: '8'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_basic_4
    - condition: numeric_state
      entity_id: sensor.fibaro_fgms001zw5_luminance
      below: 120
    - service: light.turn_on
      data:
        entity_id: light.qubino_zmnhdd1_level
        brightness: 120
    - service: light.turn_on
      entity_id: light.sonoff_basic_3

- id: belysning_paa_solned
  alias: 'Belysning på v/solnedgang'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    - service: light.turn_on
      entity_id: group.ute
    - service: light.turn_on
      entity_id: group.stemning
    - condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.galaxys8
          state: 'home'
        - condition: state
          entity_id: device_tracker.galaxys6
          state: 'home'
    - service: script.turn_on
      entity_id: script.lys_demp

- id: stemning_av
  alias: 'Stemningsbelysning av'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: light.turn_off
      entity_id: group.stemning

- id: nattsenk_paa
  alias: 'Varmekabler nattsenking'
  trigger:
    platform: time
    at: '00:23:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{{ states.climate.thermofloor_heatit_tf_021_energy_heat.attributes.temperature > 17 }}'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat
        temperature: 20
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat_2
        temperature: 20
    - delay: 09:00:00
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat
        temperature: 25
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat_2
        temperature: 24

# - id: nattsenk_av
  # alias: 'Varmekabler nattsenk av'
  # trigger:
    # platform: time
    # at: '08:00:00'
  # action:
    # - service: climate.set_temperature
      # data:
        # entity_id: climate.thermofloor_heatit_tf_021_energy_heat
        # temperature: 25
    # - service: climate.set_temperature
      # data:
        # entity_id: climate.thermofloor_heatit_tf_021_energy_heat_2
        # temperature: 24

# - id: stromspar_vvb_av
  # alias: 'Varmtvannsbereder strømsparing av'
  # trigger:
    # - platform: time
      # at: '11:00:00'
    # - platform: time
      # at: '20:00:00'
  # action:
    # - service: switch.turn_on
      # entity_id: switch.fibaro_fgwpef_switch

- id: stromspar_vvb
  alias: 'Varmtvannsbereder strømsparing'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '15:30:00'
  condition:
    - condition: template
      value_template: '{{ states.climate.thermofloor_heatit_tf_021_energy_heat.attributes.temperature > 17 }}'
  action:
    - service: switch.turn_off
      entity_id: switch.fibaro_fgwpef_switch
    - delay: 04:30:00
    - service: switch.turn_on
      entity_id: switch.fibaro_fgwpef_switch

- id: oppdatering
  alias: 'Home Assistant oppdatering'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data_template:
      title: 'Home Assistant'
      message: 'Versjon {{ states.updater.updater.state }} er tilgjengelig'
    # data:
      # data:
        # tag: 'ha-update'

- id: rpi_temp_h
  alias: 'Systemtemperatur høy'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 60
  action:
    service: notify.notify
    data:
      title: 'Home Assistant'
      message: 'Alarm: System temperatur over 60°C'

- id: rpi_temp_hh
  alias: 'Systemtemperatur kritisk'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 75
  action:
    service: notify.notify
    data:
      title: 'Home Assistant'
      message: 'Alarm: System temperatur over 75°C'

# - id: restart_modem
  # alias: 'Restart fiber modem 05:45'
  # trigger:
    # platform: time
    # at: '05:45:30'
  # action:
    # - service: switch.turn_off
      # entity_id: switch.sonoff_s20_1
    # - delay: '00:01:00'
    # - service: switch.turn_on
      # entity_id: switch.sonoff_s20_1

# - id: dingdong_aut
  # alias: "Ringeklokke trigger"
  # trigger:
    # platform: event
    # event_type: pilight_received
    # event_data:
      # protocol: c12
      # unitcode: 24
      # state: off
      # uuid: 0000-b8-27-eb-466a01
  # action:
    # - service: homeassistant.turn_on
      # entity_id: input_boolean.ringeklokke
