- id: lys_bad_paa
  alias: 'Belysning bad på v/beveglse'
  trigger:
    - platform: state
      entity_id: sensor.fibaro_fgms001zw5_burglar
      to: '8'
  condition:
    condition: numeric_state
    entity_id: sensor.fibaro_fgms001zw5_luminance
    below: 150
  action:
    - service: light.turn_on
      data:
        entity_id: light.qubino_zmnhdd1_level
        brightness: 120
    - service: light.turn_on
      entity_id: light.sonoff_basic_3

- id: lys_bad_dim
  alias: 'Belysning bad dim 10 min'
  trigger:
    platform: state
    entity_id: sensor.fibaro_fgms001zw5_burglar
    to: '0'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: light.qubino_zmnhdd1_level
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.qubino_zmnhdd1_level
        brightness: 40
    - service: light.turn_off
      entity_id: light.sonoff_basic_3

- id: lys_bad_av
  alias: 'Belysning bad av 15 min'
  trigger:
    platform: state
    entity_id: sensor.fibaro_fgms001zw5_burglar
    to: '0'
    for:
      minutes: 15
  action:
    service: light.turn_off
    entity_id: light.qubino_zmnhdd1_level

- id: utelys_stemning_paa
  alias: 'Ute- og stemningslys på v/solnedgang'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:10:00'
  action:
    - service: light.turn_on
      entity_id: group.ute
    - service: light.turn_on
      entity_id: group.stemning

- id: lys_av
  alias: 'Lys av v/soloppgang'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: group.all_lights

- id: stemning_av_uke
  alias: 'Stemningslys av 00:00 (ukedag)'
  trigger:
    platform: time
    at: '00:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: light.turn_off
    entity_id: group.stemning

- id: stemning_av_helg
  alias: 'Stemningslys av 01:30 (helg)'
  trigger:
    platform: time
    at: '01:30:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: light.turn_off
    entity_id: group.stemning

- id: nattsenk
  alias: 'Nattsenking temperatur 20°C 00:00 (ukedag)'
  trigger:
    platform: time
    at: '00:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat
        temperature: 20
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat_2
        temperature: 20

- id: dagokning
  alias: 'Dagøkning temperatur 07:00'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat
        temperature: 25
    - service: climate.set_temperature
      data:
        entity_id: climate.thermofloor_heatit_tf_021_energy_heat_2
        temperature: 24

- id: oppdatering
  alias: 'Oppdatering tilgjengelig'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data_template:
      title: 'Home Assistant'
      message: 'Versjon {{ states.updater.updater.state }} er tilgjengelig'
    # data:
      # data:
        # tag: 'ha-update'

- id: rpi_temp_h
  alias: 'Høy systemtemperatur 65°C'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 65
  action:
    service: notify.notify
    data:
      title: 'Home Assistant'
      message: 'Alarm: System temperatur over 65°C'

- id: rpi_temp_hh
  alias: 'Kritisk systemtemperatur 75°C'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperatur
    above: 75
  action:
    service: notify.notify
    data:
      title: 'Home Assistant'
      message: 'Alarm: System temperatur over 75°C'

# - id: restart_modem
  # alias: 'Restart fiber modem 05:45'
  # trigger:
    # platform: time
    # at: '05:45:30'
  # action:
    # - service: switch.turn_off
      # entity_id: switch.sonoff_s20_1
    # - delay: '00:01:00'
    # - service: switch.turn_on
      # entity_id: switch.sonoff_s20_1

# - id: dingdong_aut
  # alias: "Ringeklokke trigger"
  # trigger:
    # platform: event
    # event_type: pilight_received
    # event_data:
      # protocol: c12
      # unitcode: 24
      # state: off
      # uuid: 0000-b8-27-eb-466a01
  # action:
    # - service: homeassistant.turn_on
      # entity_id: input_boolean.ringeklokke
