homeassistant:
  name: Hjem
  latitude: !secret ha_lat
  longitude: !secret ha_long
  elevation: 58
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
switch: !include switches.yaml

# Show links to resources in log and frontend
# introduction:

# Enables support for tracking state changes over time.
# history:

# View all events in a logbook
# logbook:

# recorder:
#   purge_interval: 2

zwave:
  usb_path: /dev/ttyACM0

# Enables configuration UI
config:

# Enables the frontend
frontend:

# Checks for available updates
updater:
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

http:
  api_password: !secret http_api_password
  ssl_certificate: /etc/letsencrypt/live/hulkhaugen.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hulkhaugen.duckdns.org/privkey.pem

sun:

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - humidity

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret device_tracker_username
    password: !secret device_tracker_password
    protocol: telnet
    track_new_devices: false

# Discover some devices automatically
# discovery:

notify:
  - name: notify
    platform: html5
    gcm_api_key: !secret notify_gcm_api_key
    gcm_sender_id: !secret notify_gcm_sender_id
    
# media_player:
#   - platform: cast

# Mosquitto MQTT broker
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password
    
# ifttt:
#   key: !secret ifttt_key

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Text to speech
# tts:
#   platform: google
