homeassistant:
  name: Sagmesterveien 6
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: !secret ha_time_zone
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml

automation: !include automations.yaml
group: !include groups.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
weblink: !include weblinks.yaml
# binary_sensor:
  # - platform: mqtt
    # state_topic: "cmnd/wifi_led_controller_rgb_1/POWER2"
    # name: "WiFi LED Controller RGB 1 PIR"

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.zwave: critical
http:
  # api_password: !secret http_api_password
  base_url: !secret http_base_url
  ssl_certificate: /etc/letsencrypt/live/hulkhaugen.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hulkhaugen.duckdns.org/privkey.pem

# Mosquitto MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

zwave:
  usb_path: /dev/ttyACM0

# Enables configuration UI
config:

# Enables the map/zone
map:

# Enables the frontend
frontend:

# Checks for available updates
updater:

sun:

device_tracker:
  platform: asuswrt
  host: 192.168.1.1
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  protocol: telnet
  new_device_defaults:
    track_new_devices: false

notify:
  platform: html5
  gcm_api_key: !secret notify_gcm_api_key
  gcm_sender_id: !secret notify_gcm_sender_id

# Text to speech
tts:
  platform: google
  language: 'no'

# input_boolean:
  # ringeklokke:
    # name: 'Ringeklokke'
    # initial: off
    # icon: mdi:glassdoor

# media_player:
  # - platform: plex
  # - platform: webostv
    # host: 192.168.1.37
    # filename: webostv.conf
    # turn_on_action:
      # service: wake_on_lan.send_magic_packet
      # data:
        # mac: 10:08:C1:B6:B4:92
    # customize:
      # sources:
        # - HTPC
        # - Xbox One

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - climate
    - cover
    # - fan
    # - group
    # - input boolean
    - light
    - media_player
    - scene
    - script
    - switch

# Discover some devices automatically
# discovery:

# Enables support for tracking state changes over time.
# history:

# View all events in a logbook
# logbook:
    
# ifttt:
  # key: !secret ifttt_key

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

