homeassistant:
  name: !secret ha_name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: !secret ha_time_zone
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml

# asuswrt:
  # host: 192.168.1.1
  # username: !secret asuswrt_username
  # password: !secret asuswrt_password
  # protocol: telnet
  # port: 23

device_tracker:
  platform: asusrt
  # platform: asuswrt
  host: 192.168.1.1
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  protocol: telnet
  track_new_devices: false

automation: !include automations.yaml
config:
# conversation:
# discovery:
frontend:
google_assistant: !include google_assistant.yaml
group: !include groups.yaml
# history:
http:
  base_url: !secret http_base_url
  ssl_certificate: /etc/letsencrypt/live/hulkhaugen.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hulkhaugen.duckdns.org/privkey.pem
# ifttt:
  # key: !secret ifttt_keyinput_number: !include input_number.yaml
# input_number: !include input_number.yaml
# input_select: !include input_select.yaml
light: !include lights.yaml
# logbook:
# logger: !include logger.yaml
map:
mqtt: !include mqtt.yaml
notify:
  platform: html5
  gcm_api_key: !secret notify_gcm_api_key
  gcm_sender_id: !secret notify_gcm_sender_id
person:
# recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
sun:
switch: !include switches.yaml
system_health:
tibber:
  access_token: !secret tibber_access_token
tts:
  - platform: google
    language: 'no'
updater:
  include_used_components: true
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.133
    token: !secret xiaomi_miio_token
weather:
  - platform: met
zwave: !include zwave.yaml

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

# openuv:
  # api_key: !secret openuv_api_key
  # binary_sensors:
    # monitored_conditions:
  # sensors:
    # monitored_conditions:
      # - max_uv_index

# media_player:
  # - platform: plex
  # - platform: webostv
    # host: 192.168.1.37
    # filename: webostv.conf
    # turn_on_action:
      # service: wake_on_lan.send_magic_packet
      # data:
        # mac: 10:08:C1:B6:B4:92
    # customize:
      # sources:
        # - HTPC
        # - Xbox One