homeassistant:
  # Name of the location where Home Assistant is running
  name: Hjem
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_lat
  longitude: !secret ha_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 58
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml

# Show links to resources in log and frontend
# introduction:

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Enables support for tracking state changes over time.
# history:

# View all events in a logbook
# logbook:

# recorder:
#   purge_days: 2

zwave:
  usb_path: /dev/ttyACM0

# Enables configuration UI
config:

# Enables the frontend
frontend:

# Checks for available updates
updater:
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

http:
  api_password: !secret http_api_password
  ssl_certificate: /etc/letsencrypt/live/hulkhaugen.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hulkhaugen.duckdns.org/privkey.pem

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
    name: Været
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - humidity

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret device_tracker_username
    password: !secret device_tracker_password
    protocol: telnet
    track_new_devices: false

# Discover some devices automatically
# discovery:

notify:
  - name: Notifikasjoner
    platform: html5
    gcm_api_key: !secret notify_gcm_api_key
    gcm_sender_id: !secret notify_gcm_sender_id
    
# media_player:
#   - platform: cast

# Home Assistant embedded MQTT broker (aka MQ Telemetry Transport)
# mqtt:
    
# ifttt:
#   key: !secret ifttt_key

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Text to speech
# tts:
#   platform: google

