# Faner

default_view:
  icon: mdi:home
  name: 'Hjem'
  view: true
  entities:
  - group.scener
  - group.bad
  - group.gang
  - group.garasje
  - group.gjest
  - group.kjokken
  - group.sov
  - group.stue
  - group.utelys
  - group.teknisk

brytere:
  icon: mdi:lightbulb
  name: 'Brytere'
  view: true
  entities:
  - group.all_lights
  - group.all_switches
  - group.klima
  - group.scener
  - group.all_scripts

vaer:
  icon: mdi:weather-partlycloudy
  name: 'Været'
  view: true
  entities:
  - weather.metno
  - group.sola

multimedia:
  icon: mdi:monitor-cellphone-star
  name: 'Multimedia'
  view: true
  entities:
  - media_player.chromecast
  - media_player.google_home_mini
  - group.all_devices
  - group.radio
  - group.xbox_live

avansert:
  icon: mdi:settings
  name: 'Avansert'
  view: true
  entities:
  - group.all_automations
  - group.effekt
  - group.rpi
  - group.sensor
  - group.vaer
  - group.zwave

#1 Hjemside - default_view

scener:
  name: 'Scener'
  entities:
  - scene.belysning__alt_av
  - scene.belysning__dempet

bad:
  name: 'Bad'
  entities:
  - light.qubino_zmnhdd1_flush_dimmer_level
  - light.sb_speillys
  - switch.sb_handkletorker
  - climate.thermofloor_as_heatit_thermostat_tf_021_energy_heat

gang:
  name: 'Gang'
  entities:
  - light.wifi_smart_socket_ps16_2
  - climate.thermofloor_as_heatit_thermostat_tf_021_energy_heat_2

garasje:
  name: 'Garasje'
  entities:

gjest:
  name: 'Gjesterom / kontor'
  entities:

kjokken:
  name: 'Kjøkken'
  entities:
  - light.fibaro_system_fgd212_dimmer_2_level
  - light.fibaro_system_fgd212_dimmer_2_level_3

sov:
  name: 'Soverom'
  entities:
  - light.fibaro_system_fgd212_dimmer_2_level_10
  - light.fibaro_system_fgd212_dimmer_2_level_12
  - cover.qubino_zmnhod1_flush_shutter_dc_level
  
stue:
  name: 'Stue'
  entities:
  - light.fibaro_system_fgd212_dimmer_2_level_7
  - light.mh_hyllelys
  - light.wifi_smart_socket_ps16_3
  - light.fibaro_system_fgd212_dimmer_2_level_5
  - light.sb_gulvlampe
  - sensor.sb_gulvlampe_temperatur

teknisk:
  name: 'Teknisk'
  entities:
  - switch.fibaro_system_fgwpef_wall_plug_gen5_switch

utelys:
  name: 'Utendørs'
  entities:
  - light.sb_utelampe_n
  - light.wifi_smart_socket_ps16_1
  - light.wifi_smart_socket_ps16_4

# Brytere

klima:
  name: 'Klima'
  entities:
  - climate.thermofloor_as_heatit_thermostat_tf_021_energy_heat
  - climate.thermofloor_as_heatit_thermostat_tf_021_energy_heat_2
  - climate.remotec_zxt120eu_cooling_1
  - climate.remotec_zxt120eu_heating_1

# Været

sola:
  name: 'Sola'
  entities:
  - sun.sun
  - sensor.current_uv_index
  - sensor.current_uv_level
  - sensor.max_uv_index

# Multimedia

radio:
  name: Radio
  entities:
  - input_select.radio
  - input_select.radiokanal
  - input_number.radio_volum
  - script.radio

xbox_live:
  name: 'Xbox Live'
  entities:
  - sensor.hulkhaugen84_current
  - sensor.kayeboy_current
  - sensor.mbentzen_current

# Avansert

effekt:
  name: 'Effektforbruk'
  entities:
  - sensor.qubino_zmnhdd1_flush_dimmer_power
  - sensor.fibaro_system_fgd212_dimmer_2_power
  - sensor.fibaro_system_fgd212_dimmer_2_power_3
  - sensor.fibaro_system_fgd212_dimmer_2_power_5
  - sensor.fibaro_system_fgd212_dimmer_2_power_7
  - sensor.fibaro_system_fgd212_dimmer_2_power_10
  - sensor.fibaro_system_fgd212_dimmer_2_power_12
  - sensor.fibaro_system_fgwpef_wall_plug_gen5_power

rpi:
  name: 'Raspberry Pi 2'
  entities:
  - sensor.processor_use
  - sensor.cpu_temperatur
  - sensor.memory_use_percent
  - sensor.disk_free_root
  - sensor.disk_use_percent_root
  - sensor.ipv4_address_eth0
  - sensor.last_boot
  - updater.updater

sensor:
  name: 'Sensorer'
  entities:
  - binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
  - sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
  - sensor.fibaro_system_fgms001zw5_luminance
  - sensor.fibaro_battery_bad
  - sensor.fibaro_system_fgms001zw5_temperature
  - sensor.thermofloor_heatit_tf_021_temperature
  - sensor.thermofloor_heatit_tf_021_temperature_2
  - sensor.sb_gulvlampe_temperatur
  - sensor.sb_gulvlampe_luftfuktighet
  
zwave:
  name: 'Z-Wave'
  entities:
  - zwave.aeotec_zw090_zstick_gen5_eu
  - zwave.fibaro_system_fgd212_dimmer_2
  - zwave.fibaro_system_fgd212_dimmer_2_2
  - zwave.fibaro_system_fgd212_dimmer_2_3
  - zwave.fibaro_system_fgd212_dimmer_2_4
  - zwave.fibaro_system_fgd212_dimmer_2_5
  - zwave.fibaro_system_fgd212_dimmer_2_6
  - zwave.fibaro_system_fgms001zw5_motion_sensor
  - zwave.fibaro_system_fgwpef_wall_plug_gen5
  - zwave.qubino_zmnhdd1_flush_dimmer
  - zwave.qubino_zmnhod1_flush_shutter_dc
  - zwave.remotec_zxt120eu
  - zwave.thermofloor_as_heatit_thermostat_tf_021
  - zwave.thermofloor_as_heatit_thermostat_tf_021_2

# Skjult

personer:
  name: 'Personer'
  entities:
  - device_tracker.galaxys8_bh
  - device_tracker.galaxys8_cg

stemning:
  name: 'Stemningsbelysning'
  entities:
  - light.mh_hyllelys
  - light.sb_gulvlampe
  - light.wifi_smart_socket_ps16_2
  - light.wifi_smart_socket_ps16_3
