default_view:
  name: 'Hjem'
  view: true
  entities:
  - group.scener
  - group.bad
  - group.gang
  - group.kjokken
  - group.kontor
  - group.sov
  - group.stue
  - group.garasje
  - group.ute
  - group.teknisk

# media_spillere:
  # name: 'Medieavspillere'
  # view: true
  # entities:
  # - media_player.brrecast
  # - media_player.gpm_desktop_player
  # - media_player.lg_webos_smart_tv
  # - media_player.google_home_mini
  # - media_player.plex_web_chrome

avansert:
  name: 'Avansert'
  view: true
  entities:
  - group.all_automations
  - group.all_devices
  - group.all_lights
  - group.all_scripts
  - group.all_switches
  - group.klima
  - group.vaer
  - group.rgb_led
  - group.stemning

diagnose:
  name: 'Diagnose'
  view: true
  entities:
  - group.rpi
  - group.sensor
  - group.zwave

bad:
  name: 'Bad'
  entities:
  - light.sonoff_basic_3
  - light.qubino_zmnhdd1_level
  - switch.sonoff_basic_4
  - climate.thermofloor_heatit_tf_021_energy_heat

gang:
  name: 'Gang'
  entities:
  - climate.thermofloor_heatit_tf_021_energy_heat_2
  - light.wifi_smart_socket_ps16_2

garasje:
  name: 'Garasje'
  entities:

kjokken:
  name: 'Kjøkken'
  entities:
  - light.fibaro_fgd212_level
  - light.fibaro_fgd212_level_3

klima:
  name: 'Klima'
  entities:
  - climate.thermofloor_heatit_tf_021_energy_heat
  - climate.thermofloor_heatit_tf_021_energy_heat_2
  - climate.remotec_zxt120eu_cooling_1
  - climate.remotec_zxt120eu_heating_1

kontor:
  name: 'Gjesterom / kontor'
  entities:
  - light.wifi_smart_bulb_1

vaer:
  name: 'Været'
  entities:
  - sun.sun
  - sensor.yr_symbol
  - sensor.yr_temperature
  - sensor.yr_wind_speed
  - sensor.yr_humidity
  - sensor.yr_pressure

rgb_led:
  name: 'RGB LED Belysning'
  entities:
  - light.wifi_smart_bulb_1
  - light.wifi_smart_bulb_2
  - light.wifi_smart_bulb_3

rpi:
  name: 'Raspberry Pi 2'
  entities:
  - device_tracker.raspberry_pi_2
  - sensor.processor_use
  - sensor.cpu_temperatur
  - sensor.memory_use_percent
  - sensor.disk_free_root
  - sensor.disk_use_percent_root
  - sensor.ipv4_address_eth0
  - sensor.time
  - sensor.date
  - sensor.last_boot
  - updater.updater

scener:
  name: 'Scener'
  entities:
  - scene.belysning__alt_av
  - scene.belysning__arbeid
  - scene.belysning__dempet

sensor:
  name: 'Sensorer'
  entities:
  - sensor.fibaro_fgms001zw5_burglar
  - sensor.fibaro_fgms001zw5_luminance
  - sensor.fibaro_battery_bad
  - sensor.fibaro_fgms001zw5_temperature
  - sensor.thermofloor_heatit_tf_021_temperature
  - sensor.thermofloor_heatit_tf_021_temperature_2
  - sensor.sonoff_basic_2_dht22_temperature
  - sensor.sonoff_basic_2_dht22_humidity

sov:
  name: 'Soverom'
  entities:

stemning:
  name: 'Stemningsbelysning'
  entities:
  - light.sonoff_basic_2
  - light.wifi_smart_socket_ps16_2
  - light.wifi_smart_socket_ps16_3
  
stue:
  name: 'Stue'
  entities:
  - light.fibaro_fgd212_level_5
  - light.sonoff_basic_2
  - light.wifi_smart_socket_ps16_3
  - sensor.sonoff_basic_2_dht22_temperature

teknisk:
  name: 'Teknisk'
  entities:
  - device_tracker.galaxys8
  - device_tracker.galaxys6
  - switch.fibaro_fgwpef_switch

ute:
  name: 'Utendørs'
  entities:
  - light.sonoff_basic_5
  - light.wifi_smart_socket_ps16_1
  - light.wifi_smart_socket_ps16_4

zwave:
  name: 'Z-Wave'
  entities:
  - zwave.aeotec_zw090_zstick_gen5_eu
  - zwave.fibaro_system_fgd212_dimmer_2
  - zwave.fibaro_system_fgd212_dimmer_2_2
  - zwave.fibaro_system_fgd212_dimmer_2_3
  - zwave.fibaro_system_fgms001zw5_motion_sensor
  - zwave.fibaro_system_fgwpef_wall_plug_gen5
  - zwave.qubino_zmnhdd1_flush_dimmer
  - zwave.remotec_zxt120eu
  - zwave.thermofloor_as_heatit_thermostat_tf_021
  - zwave.thermofloor_as_heatit_thermostat_tf_021_2
