- platform: mqtt
  name: "SB Gulvlampe"
  command_topic: "cmnd/sb_gulvlampe/POWER1"
  state_topic: "stat/sb_gulvlampe/POWER1"
  availability_topic: "tele/sb_gulvlampe/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "SB Speillys"
  command_topic: "cmnd/sb_speillys/POWER"
  state_topic: "stat/sb_speillys/POWER"
  availability_topic: "tele/sb_speillys/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "SB Utelampe N"
  command_topic: "cmnd/sb_utelampe_n/POWER"
  state_topic: "stat/sb_utelampe_n/POWER"
  availability_topic: "tele/sb_utelampe_n/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 1"
  command_topic: "cmnd/wifi_smart_socket_ps-16_1/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_1/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 2"
  command_topic: "cmnd/wifi_smart_socket_ps-16_2/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_2/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 3"
  command_topic: "cmnd/wifi_smart_socket_ps-16_3/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_3/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_3/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 4"
  command_topic: "cmnd/wifi_smart_socket_ps-16_4/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_4/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_4/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "MH Hyllelys"
  state_topic: "stat/mh_hyllelys/POWER1"
  command_topic: "cmnd/mh_hyllelys/POWER1"
  availability_topic: "tele/mh_hyllelys/LWT"
  brightness_state_topic: "stat/mh_hyllelys/RESULT"
  brightness_command_topic: "cmnd/mh_hyllelys/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  retain: true
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
