- platform: group
  name: Innelys
  entities:
  - light.sb_speillys
  - light.qubino_zmnhdd1_flush_dimmer_level
  - light.fibaro_system_fgd212_dimmer_2_level
  - light.fibaro_system_fgd212_dimmer_2_level_3
  - light.fibaro_system_fgd212_dimmer_2_level_5
  - light.fibaro_system_fgd212_dimmer_2_level_7
  - light.fibaro_system_fgd212_dimmer_2_level_10
  - light.fibaro_system_fgd212_dimmer_2_level_12
  - light.fibaro_system_fgd212_dimmer_2_level_14
  - light.mh_hyllelys

- platform: group
  name: Utelys
  entities:
  # - light.sb_utelampe_n
  - light.wifi_smart_socket_ps16_1
  - light.wifi_smart_socket_ps16_4
  - light.wifi_smart_socket_ps16_5

- platform: group
  name: Stemningslys
  entities:
  - light.sb_gulvlampe
  - light.wifi_smart_socket_ps16_2
  - light.wifi_smart_socket_ps16_3
  - light.sonoff_s20_2


- platform: mqtt
  name: "SB Gulvlampe"
  command_topic: "cmnd/sb_gulvlampe/POWER1"
  state_topic: "stat/sb_gulvlampe/POWER1"
  availability_topic: "tele/sb_gulvlampe/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "SB Speillys"
  command_topic: "cmnd/sb_speillys/POWER1"
  state_topic: "stat/sb_speillys/POWER1"
  availability_topic: "tele/sb_speillys/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

# - platform: mqtt
  # name: "SB Utelampe N"
  # command_topic: "cmnd/sb_utelampe_n/POWER1"
  # state_topic: "stat/sb_utelampe_n/POWER1"
  # availability_topic: "tele/sb_utelampe_n/LWT"  
  # qos: 1
  # payload_available: "Online"
  # payload_not_available: "Offline"

- platform: mqtt
  name: "WiFi Smart Socket PS16 1"
  command_topic: "cmnd/wifi_smart_socket_ps-16_1/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_1/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "WiFi Smart Socket PS16 2"
  command_topic: "cmnd/wifi_smart_socket_ps-16_2/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_2/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "WiFi Smart Socket PS16 3"
  command_topic: "cmnd/wifi_smart_socket_ps-16_3/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_3/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_3/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "WiFi Smart Socket PS16 4"
  command_topic: "cmnd/wifi_smart_socket_ps-16_4/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_4/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_4/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

# - platform: mqtt
  # name: "Sonoff S20 1"
  # command_topic: "cmnd/sonoff_s20_1/POWER1"
  # state_topic: "stat/sonoff_s20_1/POWER1"
  # availability_topic: "tele/sonoff_s20_1/LWT"  
  # qos: 1
  # payload_available: "Online"
  # payload_not_available: "Offline"

- platform: mqtt
  name: "Sonoff S20 2"
  command_topic: "cmnd/sonoff_s20_2/POWER1"
  state_topic: "stat/sonoff_s20_2/POWER1"
  availability_topic: "tele/sonoff_s20_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

# - platform: mqtt
  # name: "Sonoff S20 3"
  # command_topic: "cmnd/sonoff_s20_3/POWER1"
  # state_topic: "stat/sonoff_s20_3/POWER1"
  # availability_topic: "tele/sonoff_s20_3/LWT"  
  # qos: 1
  # payload_available: "Online"
  # payload_not_available: "Offline"

- platform: mqtt
  name: "WiFi Smart Socket PS16 5"
  command_topic: "cmnd/wifi_smart_socket_ps-16_5/POWER1"
  state_topic: "stat/wifi_smart_socket_ps-16_5/POWER1"
  availability_topic: "tele/wifi_smart_socket_ps-16_5/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

# - platform: mqtt
  # name: "WiFi Smart Socket PS16 6"
  # command_topic: "cmnd/wifi_smart_socket_ps-16_6/POWER1"
  # state_topic: "stat/wifi_smart_socket_ps-16_6/POWER1"
  # availability_topic: "tele/wifi_smart_socket_ps-16_6/LWT"  
  # qos: 1
  # payload_available: "Online"
  # payload_not_available: "Offline"

- platform: mqtt
  name: "MH Hyllelys"
  state_topic: "stat/mh_hyllelys/POWER1"
  command_topic: "cmnd/mh_hyllelys/POWER1"
  availability_topic: "tele/mh_hyllelys/LWT"
  brightness_state_topic: "stat/mh_hyllelys/RESULT"
  brightness_command_topic: "cmnd/mh_hyllelys/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
