- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - pressure
    - humidity

- platform: template
  sensors:
    fibaro_battery_bad:
      friendly_name: 'Multisensor batteri bad'
      value_template:
        '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor %}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
        {% else %}
          Ikke tilgjengelig
        {% endif %}'
      unit_of_measurement: '%'


- platform: command_line
  name: 'CPU temperatur'
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /root
    - type: disk_free
      arg: /root
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: time_date
  display_options:
    - time
    - date

- platform: mqtt
  name: "Sonoff Basic 2 DHT22 Temperature"
  state_topic: "tele/sonoff_basic_2/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Sonoff Basic 2 DHT22 Humidity"
  state_topic: "tele/sonoff_basic_2/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"
