- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - pressure
    - humidity

- platform: xbox_live
#  api_key: !secret xbox_live_api_key 
  api_key: d84c509e072ce1ad0b62230af5304c0e67086b46
  scan_interval: 300
  xuid:
  #Extracted from e.g: https://xboxapi.com/v2/xuid/hulkhaugen84 --> 2533274836441831
#    - 2533274934106454
#    - 2535409873827380
    - 2533274836441831
#    - 2533274798318388
#    - 2533274997028457

#- platform: template
#  sensors:
#    xboxapi_current:
#      friendly_name: 'Xbox One X'
#      value_template: '{% if is_state("sensor.pawnynz", "Offline") %}Offline{% else %}{{ states.sensor.hulkahugen84.attributes["XboxOne Full"] }}{% endif %}'

- platform: template
  sensors:
    fibaro_battery_bad:
      friendly_name: 'Multisensor batteri bad'
      value_template:
        '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor %}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
        {% else %}
          Ikke tilgjengelig
        {% endif %}'
      unit_of_measurement: '%'

- platform: command_line
  name: 'CPU temperatur'
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /root
    - type: disk_free
      arg: /root
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: time_date
  display_options:
    - time
    - date

- platform: mqtt
  name: "SB Gulvlampe Temperatur"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "SB Gulvlampe Luftfuktighet"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"
