- platform: xbox_live
  api_key: !secret xbox_live_api_key 
  scan_interval: 300
  xuid:
  #Extracted from e.g: https://xboxapi.com/v2/xuid/hulkhaugen84 --> 2533274836441831
   # - 2533274934106454 ElgenHaugen
   # - 2535409873827380 Finnsa197
   - 2533274836441831
   - 2533274798318388
   # - 2533274997028457

- platform: template
  sensors:
    hulkhaugen84_current:
      friendly_name_template: '{{ states.sensor.hulkhaugen84.attributes["friendly_name"] }}'
      value_template:
        '{% if is_state("sensor.hulkhaugen84", "Offline") %}
          Borte
        {% else %}
          {{ states.sensor.hulkhaugen84.attributes["XboxOne Full"] }}
        {% endif %}'
      entity_picture_template: '{{ states.sensor.hulkhaugen84.attributes["entity_picture"] }}'

- platform: template
  sensors:
    kayeboy_current:
      friendly_name_template: '{{ states.sensor.kayeboy.attributes["friendly_name"] }}'
      value_template:
        '{% if is_state("sensor.kayeboy", "Offline") %}
          Borte
        {% else %}
          {{ states.sensor.kayeboy.attributes["XboxOne Full"] }}
        {% endif %}'
      entity_picture_template: '{{ states.sensor.kayeboy.attributes["entity_picture"] }}'

# - platform: template
  # sensors:
    # mbentzen_current:
      # friendly_name_template: '{{ states.sensor.mbentzen.attributes["friendly_name"] }}'
      # value_template:
        # '{% if is_state("sensor.mbentzen", "Offline") %}
          # Borte
        # {% else %}
          # {{ states.sensor.mbentzen.attributes["XboxOne Full"] }}
        # {% endif %}'
      # entity_picture_template: '{{ states.sensor.mbentzen.attributes["entity_picture"] }}'

- platform: template
  sensors:
    fibaro_battery_bad:
      friendly_name: 'Multisensor batteri bad'
      value_template:
        '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor %}
          {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
        {% else %}
          Ikke tilgjengelig
        {% endif %}'
      unit_of_measurement: '%'

- platform: command_line
  name: 'CPU temperatur'
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /root
    - type: disk_free
      arg: /root
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

- platform: mqtt
  name: "SB Gulvlampe Temperatur"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "SB Gulvlampe Luftfuktighet"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"
