# - platform: xbox_live
  # api_key: !secret xbox_live_api_key 
  # scan_interval: 300
  # command_timeout: 30
  # timeout: 30
  # xuid:
  #Extracted from e.g: https://xboxapi.com/v2/xuid/hulkhaugen84 --> 2533274836441831
   # - 2533274934106454 ElgenHaugen
   # - 2535409873827380 Finnsa197
   # - 2533274836441831
   # - 2533274798318388
   # - 2533274997028457

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /root
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

# - platform: alpha_vantage
  # api_key: !secret alpha_vantage_api_key
  # symbols:
    # - symbol: GOOGL
      # name: Google

- platform: mqtt
  name: "SB Gulvlampe Temperatur"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "SB Gulvlampe Luftfuktighet"
  state_topic: "tele/sb_gulvlampe/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"

- platform: template
  sensors:

    dnb_ask_beholding:
      friendly_name: 'Aksjesparekonto'
      unit_of_measurement: "kr"
      value_template: "{{('{0:,.2f}'.format((10956.0810 * (states('sensor.dnb_teknologi_r_kurs')|replace(',','.')|float)) + (4154.6530 * (states('sensor.dnb_health_care_r_kurs')|replace(',','.')|float)))|replace(',',' ')|replace('.',','))}}"

    vindstyrke_tekst:
      friendly_name: 'Vindstyrke'
      value_template: >
        {% set vind = (states.weather.met_no.attributes["wind_speed"]|float/3.6)|round(1) %}
          {% if   vind|float <   0.5 %}Stille, {{vind}} m/s
          {% elif vind|float <   1.5 %}Flau vind, {{vind}} m/s
          {% elif vind|float <   3.3 %}Svak vind, {{vind}} m/s
          {% elif vind|float <   5.5 %}Lett bris, {{vind}} m/s
          {% elif vind|float <   7.9 %}Laber bris, {{vind}} m/s
          {% elif vind|float <  10.7 %}Frisk bris, {{vind}} m/s
          {% elif vind|float <  13.8 %}Liten kuling, {{vind}} m/s
          {% elif vind|float <  17.1 %}Stiv kuling, {{vind}} m/s
          {% elif vind|float <  20.7 %}Sterk kuling, {{vind}} m/s
          {% elif vind|float <  24.5 %}Liten storm, {{vind}} m/s
          {% elif vind|float <  28.4 %}Full storm, {{vind}} m/s
          {% elif vind|float <  32.6 %}Sterk storm, {{vind}} m/s
          {% elif vind|float >= 32.6 %}Orkan, {{vind}} m/s
          {% else %} {{vind}} m/s
        {% endif %}
      icon_template: >-
        {% if states.weather.met_no.attributes["wind_speed"]|float < 1.08 %} mdi:circle-outline
        {% else %} mdi:weather-windy
        {% endif %}

    sunrise_sunset:
      friendly_name: 'Solhendelse'
      value_template: >
        {% if states.sun.sun.attributes["next_rising"] < states.sun.sun.attributes["next_setting"] %}
          Soloppgang {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}
        {% else %}
          Solnedgang {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}
        {% endif %}
      icon_template: >-
        {% if states.sun.sun.attributes["next_rising"] < states.sun.sun.attributes["next_setting"] %} mdi:weather-sunset-up
        {% else %} mdi:weather-sunset-down
        {% endif %}

    uv_niva:
      friendly_name: 'UV nivå'
      value_template: >-
        {% set max_uv = states.sensor.max_uv_index.state|round(1) %}
          {% if   max_uv|float <=  2 %}Lav UV indeks, {{max_uv}}
          {% elif max_uv|float <=  5 %}Moderat UV indeks, {{max_uv}}
          {% elif max_uv|float <=  7 %}Sterk UV indeks, {{max_uv}}
          {% elif max_uv|float <= 10 %}Svært sterk UV indeks, {{max_uv}}
          {% elif max_uv|float >  10 %}Ekstrem UV indeks, {{max_uv}}
          {% else %} Ukjent UV nivå
        {% endif %}
      icon_template: >-
        {% if states.sensor.max_uv_index.state|float <= 5 %}
          mdi:weather-sunny
        {% else %}
          mdi:sunglasses
        {% endif %}
        
    stromforbruk_t:
      friendly_name: 'Strømforbruk'
      unit_of_measurement: "kr/t"
      value_template: "{{'{0:,.2f}'.format(states('sensor.real_time_consumption_sagmesterveien_6')|float * states('sensor.electricity_price_sagmesterveien_6')|float / 1000 )}}"
      icon_template: >-
          {% if states.sensor.electricity_price_sagmesterveien_6.state|float < 0.5 %} mdi:coins
          {% else %} mdi:cash
          {% endif %}
    # tibber_use:
      # friendly_name: 'Estimert forbruk'
      # unit_of_measurement: "kr/år"
      # value_template: "{{'{:,.2f}'.format(states.sensor.electricity_price_sagmesterveien_6.attributes["estimated_annual_consumption"])}}"
    # tibber_min:
      # friendly_name: 'Strømpris lav'
      # unit_of_measurement: "kr/kWh"
      # value_template: "{{'{:.2f}'.format(states.sensor.electricity_price_sagmesterveien_6.attributes["min_price"])}}"
    # tibber_max:
      # friendly_name: 'Strømpris høy'
      # unit_of_measurement: "kr/kWh"
      # value_template: "{{'{:.2f}'.format(states.sensor.electricity_price_sagmesterveien_6.attributes["max_price"])}}"
    # tibber_avg:
      # friendly_name: 'Strømpris snitt'
      # unit_of_measurement: "kr/kWh"
      # value_template: "{{'%0.2f' % ((float(states.sensor.electricity_price_sagmesterveien_6.attributes["min_price"])+float(states.sensor.electricity_price_sagmesterveien_6.attributes["max_price"]))/2 )}}"
    # tibber_volt:
      # friendly_name: 'Spenning'
      # unit_of_measurement: "V"
      # value_template: "{{states.sensor.real_time_consumption_sagmesterveien_6.attributes["voltagePhase1"]}}"
    # tibber_amp:
      # friendly_name: 'Strømtrekk'
      # unit_of_measurement: "A"
      # value_template: "{{states.sensor.real_time_consumption_sagmesterveien_6.attributes["currentPhase1"]}}"

    # hulkhaugen84_current:
      # friendly_name_template: '{{ states.sensor.hulkhaugen84.attributes["friendly_name"] }}'
      # value_template:
        # '{% if states.sensor.hulkhaugen84.attributes["XboxOne Full"] is defined %} 
          # {{ states.sensor.hulkhaugen84.attributes["XboxOne Full"] }}
        # {% elif states.sensor.hulkhaugen84.attributes["XboxOne Background"] is defined %} 
          # Xbox One: {{ states.sensor.hulkhaugen84.attributes["XboxOne Background"] }}
        # {% elif states.sensor.hulkhaugen84.attributes["WindowsOneCore Full"] is defined %} 
          # Windows: {{ states.sensor.hulkhaugen84.attributes["WindowsOneCore Full"] }}
        # {% elif states.sensor.hulkhaugen84.attributes["Android Full"] is defined %} 
          # Android: {{ states.sensor.hulkhaugen84.attributes["Android Full"] }}
        # {% else %}
          # Borte
        # {% endif %}'
      # entity_picture_template: '{{ states.sensor.hulkhaugen84.attributes["entity_picture"] }}'
    # kayeboy_current:
      # friendly_name_template: '{{ states.sensor.kayeboy.attributes["friendly_name"] }}'
      # value_template:
        # '{% if states.sensor.kayeboy.attributes["XboxOne Full"] is defined %} 
          # {{ states.sensor.kayeboy.attributes["XboxOne Full"] }}
        # {% elif states.sensor.kayeboy.attributes["XboxOne Background"] is defined %} 
          # Xbox One: {{ states.sensor.kayeboy.attributes["XboxOne Background"] }}
        # {% elif states.sensor.kayeboy.attributes["WindowsOneCore Full"] is defined %} 
          # Windows: {{ states.sensor.kayeboy.attributes["WindowsOneCore Full"] }}
        # {% elif states.sensor.kayeboy.attributes["Android Full"] is defined %} 
          # Android: {{ states.sensor.kayeboy.attributes["Android Full"] }}
        # {% else %}
          # Borte
        # {% endif %}'
      # entity_picture_template: '{{ states.sensor.kayeboy.attributes["entity_picture"] }}'
    # mbentzen_current:
      # friendly_name_template: '{{ states.sensor.mbentzen.attributes["friendly_name"] }}'
      # value_template:
        # '{% if states.sensor.mbentzen.attributes["XboxOne Full"] is defined %} 
          # {{ states.sensor.mbentzen.attributes["XboxOne Full"] }}
        # {% elif states.sensor.mbentzen.attributes["XboxOne Background"] is defined %} 
          # Xbox One: {{ states.sensor.mbentzen.attributes["XboxOne Background"] }}
        # {% elif states.sensor.mbentzen.attributes["WindowsOneCore Full"] is defined %} 
          # Windows: {{ states.sensor.mbentzen.attributes["WindowsOneCore Full"] }}
        # {% elif states.sensor.mbentzen.attributes["Android Full"] is defined %} 
          # Android: {{ states.sensor.mbentzen.attributes["Android Full"] }}
        # {% else %}
          # Borte
        # {% endif %}'
      # entity_picture_template: '{{ states.sensor.mbentzen.attributes["entity_picture"] }}'

    # fibaro_battery_bad:
      # friendly_name: 'Multisensor batteri bad'
      # value_template:
        # '{% if states.zwave.fibaro_system_fgms001zw5_motion_sensor %}
          # {{ states.zwave.fibaro_system_fgms001zw5_motion_sensor.attributes.battery_level }}
        # {% else %}
          # Ikke tilgjengelig
        # {% endif %}'
      # unit_of_measurement: '%'

- platform: command_line
  name: 'CPU temperatur'
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: 'DNB Global Indeks 1 dag'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000JORS&tab=1" | grep "1 dag" | awk -F'value number\">' '{ print $2 }' | awk -F'</td>' '{ print $1  }'
  unit_of_measurement: "%"
  scan_interval: 1800
  command_timeout: 30

- platform: command_line
  name: 'DNB Health Care R 1 dag'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000ZFFV&tab=1" | grep "1 dag" | awk -F'value number\">' '{ print $2 }' | awk -F'</td>' '{ print $1  }'
  unit_of_measurement: "%"
  scan_interval: 900
  command_timeout: 30

- platform: command_line
  name: 'DNB Health Care R kurs'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000ZFFV" | grep "NAV" | awk -F'line text\">' '{ print $2 }' | awk -F'</td>' '{ print substr($1, length($1)-5)}'
  unit_of_measurement: "kr"
  scan_interval: 900
  command_timeout: 30

- platform: command_line
  name: 'DNB Norge Indeks 1 dag'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000JORR&tab=1" | grep "1 dag" | awk -F'value number\">' '{ print $2 }' | awk -F'</td>' '{ print $1  }'
  unit_of_measurement: "%"
  scan_interval: 1800
  command_timeout: 30

- platform: command_line
  name: 'DNB Teknologi R 1 dag'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000ZFG1&tab=1" | grep "1 dag" | awk -F'value number\">' '{ print $2 }' | awk -F'</td>' '{ print $1  }'
  unit_of_measurement: "%"
  scan_interval: 900
  command_timeout: 30

- platform: command_line
  name: 'DNB Teknologi R kurs'
  command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000ZFG1" | grep "NAV" | awk -F'line text\">' '{ print $2 }' | awk -F'</td>' '{ print substr($1, length($1)-5)}'
  unit_of_measurement: "kr"
  scan_interval: 900
  command_timeout: 30

# - platform: command_line
  # name: 'DNB Teknologi 1 uke'
  # command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F0GBR04NGU&tab=1" | grep "1 uke" | awk -F'value number\">' '{ print $3 }' | awk -F'</td>' '{ print $1  }'
  # unit_of_measurement: "%"
  # scan_interval: 600
  # command_timeout: 30

# - platform: command_line
  # name: 'DNB Teknologi 1 mnd'
  # command: curl -sSL "http://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F0GBR04NGU&tab=1" | grep "1 måned" | awk -F'value number\">' '{ print $3 }' | awk -F'</td>' '{ print $1  }'
  # unit_of_measurement: "%"
  # scan_interval: 600
  # command_timeout: 30

- platform: rest
  name: 'Home Assistant versjon'
  json_attributes:
   - release_title
   - release_description
   - release_notes
  resource: https://www.home-assistant.io/version.json
  value_template: '{{ value_json.current_version }}'