- platform: mqtt
  name: "Sonoff 1"
  command_topic: "cmnd/sonoff1/power"
  state_topic: "stat/sonoff1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Sonoff 2"
  command_topic: "cmnd/sonoff2/power"
  state_topic: "stat/sonoff2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Sonoff 3"
  command_topic: "cmnd/sonoff3/power"
  state_topic: "stat/sonoff3/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true