- platform: mqtt
  name: "Sonoff Basic 1"
  command_topic: "cmnd/sonoff_basic_1/POWER"
  state_topic: "stat/sonoff_basic_1/POWER"
  availability_topic: "tele/sonoff_basic_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Basic 4"
  command_topic: "cmnd/sonoff_basic_4/POWER"
  state_topic: "stat/sonoff_basic_4/POWER"
  availability_topic: "tele/sonoff_basic_4/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Basic 6"
  command_topic: "cmnd/sonoff_basic_6/POWER"
  state_topic: "stat/sonoff_basic_6/POWER"
  availability_topic: "tele/sonoff_basic_6/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Basic 7"
  command_topic: "cmnd/sonoff_basic_7/POWER"
  state_topic: "stat/sonoff_basic_7/POWER"
  availability_topic: "tele/sonoff_basic_7/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Basic 8"
  command_topic: "cmnd/sonoff_basic_8/POWER"
  state_topic: "stat/sonoff_basic_8/POWER"
  availability_topic: "tele/sonoff_basic_8/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Dual R2 1.1"
  command_topic: "cmnd/sonoff_dual_r2_1/POWER1"
  state_topic: "stat/sonoff_dual_r2_1/POWER1"
  availability_topic: "tele/sonoff_dual_r2_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Dual R2 1.2"
  command_topic: "cmnd/sonoff_dual_r2_1/POWER2"
  state_topic: "stat/sonoff_dual_r2_1/POWER2"
  availability_topic: "tele/sonoff_dual_r2_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Dual R2 2.1"
  command_topic: "cmnd/sonoff_dual_r2_2/POWER1"
  state_topic: "stat/sonoff_dual_r2_2/POWER1"
  availability_topic: "tele/sonoff_dual_r2_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff Dual R2 2.2"
  command_topic: "cmnd/sonoff_dual_r2_2/POWER2"
  state_topic: "stat/sonoff_dual_r2_2/POWER2"
  availability_topic: "tele/sonoff_dual_r2_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff S20 1"
  command_topic: "cmnd/sonoff_s20_1/POWER"
  state_topic: "stat/sonoff_s20_1/POWER"
  availability_topic: "tele/sonoff_s20_1/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff S20 2"
  command_topic: "cmnd/sonoff_s20_2/POWER"
  state_topic: "stat/sonoff_s20_2/POWER"
  availability_topic: "tele/sonoff_s20_2/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Sonoff S20 3"
  command_topic: "cmnd/sonoff_s20_3/POWER"
  state_topic: "stat/sonoff_s20_3/POWER"
  availability_topic: "tele/sonoff_s20_3/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 5"
  command_topic: "cmnd/wifi_smart_socket_ps-16_5/POWER"
  state_topic: "stat/wifi_smart_socket_ps-16_5/POWER"
  availability_topic: "tele/wifi_smart_socket_ps-16_5/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "WiFi Smart Socket PS-16 6"
  command_topic: "cmnd/wifi_smart_socket_ps-16_6/POWER"
  state_topic: "stat/wifi_smart_socket_ps-16_6/POWER"
  availability_topic: "tele/wifi_smart_socket_ps-16_6/LWT"  
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

# - platform: rpi_rf
 # gpio: 17
 # switches:
   # ringeklokke:
     # protocol: 1
     # pulselength: 218
     ## pulselength: 219
     # code_on: 89940
